## Installing PyTorch

In [1]:
!pip install torch

## Checking Version

In [2]:
import torch

print(torch.__version__)

2.9.1+cu128


In [3]:
!nvidia-smi

Sat Jan 10 20:23:36 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:C4:00.0 Off |                  N/A |
| N/A   42C    P3              8W /   45W |       9MiB /   6141MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introduction to Tensors

### Creating tensors

In [4]:
# scalar

scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

10

In [7]:
# vector

vector = torch.tensor([10,10])
vector

tensor([10, 10])

In [9]:
vector.ndim

1

In [12]:
# MATRIX

MATRIX = torch.tensor([[1,2],
                      [4,5]])
MATRIX

tensor([[1, 2],
        [4, 5]])

In [13]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [32]:
# Creating a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3188, 0.0027, 0.0497, 0.4596],
        [0.4363, 0.3081, 0.3639, 0.3399],
        [0.9135, 0.1861, 0.2974, 0.3974]])

In [33]:
random_tensor.ndim

2

In [34]:
# Create a random tensor with similar shape as a image tensor

random_size_image_tensor = torch.rand(224,224, 3) # Height, Width, Channel
random_size_image_tensor.shape, random_size_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [35]:
# creating a tensor with all zeros

zeros = torch.zeros(3,1)
zeros

tensor([[0.],
        [0.],
        [0.]])

In [36]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Create a range of tensors

In [38]:
one_to_ten = torch.arange(start = 1,end = 11,step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# Creating tensors like

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [46]:
float32_tensor = torch.tensor([1.0,3.0,7.0],
                           dtype = None,   # What datatype is your tensor
                           device = None,  # what device is youor tensor on
                           requires_grad = False) # whether or not to track gradience with this tensor operations
float32_tensor

tensor([1., 3., 7.])

In [47]:
float32_tensor.dtype

torch.float32

In [49]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([1., 3., 7.], dtype=torch.float16)

In [53]:
# Find out details about some tensor

print(float16_tensor)
print(f"dtype of tensor: {float16_tensor.dtype}")
print(f"Shape of tensor: {float16_tensor.shape}")
print(f"device tensor is on: {float16_tensor.device}")

tensor([1., 3., 7.], dtype=torch.float16)
dtype of tensor: torch.float16
Shape of tensor: torch.Size([3])
device tensor is on: cpu
