In [1]:
import torch

### Tensor Manipulation

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [2]:
# Tensor creation

tensor = torch.tensor([1,2,3])

tensor

tensor([1, 2, 3])

In [3]:
# Tensor Addition

torch.add(tensor, 10)

tensor + 10

tensor([11, 12, 13])

In [4]:
# Tensor Multiply

torch.mul(tensor, 10)

tensor * 10

tensor([10, 20, 30])

In [5]:
# Tensor Subtract

torch.sub(tensor, 10)

tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

In [9]:
# Element wise multiplication 

print(tensor,'*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [10]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [20]:
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

In [21]:
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [25]:
print(tensor_A.shape)
print(tensor_A.T.shape)

torch.Size([2, 3])
torch.Size([3, 2])


In [26]:
# The matrix multiplication works when matrix b in Transposed

torch.matmul(tensor_A, tensor_B.T)

tensor([[0.2146, 0.3910],
        [0.5412, 0.1505]])

### Aggregation functions

In [28]:
# Creating a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
# Find the min

x.min(), torch.min(x)

(tensor(0), tensor(0))

In [30]:
# Find the max

x.max(), torch.max(x)

(tensor(90), tensor(90))

In [33]:
# Find the mean

x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [35]:
# Find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### Finding the positional min max

In [40]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
# Finds the min value and gives the index of it, as an output.

x.argmin()

tensor(0)

In [38]:
x[0]

tensor(0)

In [37]:
# Finds the max value and gives the index of it, as an output.

x.argmax()

tensor(9)

In [39]:
x[9]

tensor(90)