In [1]:
import torch

### Tensor Manipulation 

* Reshaping - reshapes an input tensor to a defined shape
* View - Return of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) ot side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimention to a target tensor
* Permute - Return a view of the inpit with dimensions permuted (swapped) in an certain way

In [6]:
# Creating an tensor

y = torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [7]:
# reshape

y_reshaped = y.reshape(1,9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [9]:
# View

z = y.view(1,9)
z, z.shape

# Changing z changed y (because a view of a tensor shares the same memory as the original input)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [15]:
# Stack tensor on top of each other

y_stacking  = torch.stack([y,y,y,y], dim=0)
y_stacking , y_stacking.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [16]:
# torch.squeeze() - It removes all single dimentions of a target tensor

y_squeezed = y_reshaped.squeeze()

print(f"Original tensor: {y_reshaped}")
print(f"Original shape: {y_reshaped.shape}")

print(f"\nNew tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")

Original tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Original shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [19]:
# torch.unsqueeze() - Adds single dimention to a target tensor

y_unsqueezed = y_reshaped.unsqueeze(dim = 0)

print(f"Original tensor: {y_reshaped}")
print(f"Original shape: {y_reshaped.shape}")

print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Original tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Original shape: torch.Size([1, 9])

New tensor: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
New shape: torch.Size([1, 1, 9])


In [22]:
# torch.permute() - rearanges the dimentions of a target tensor in a specific order

x_original = torch.rand(size=(224,224,3)) # Height, Width, Channels
x_permute = x_original.permute(2,0,1)
print(f"Previous shape: {x_original.shape}")
print(f"new shape: {x_permute.shape}")


Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])
