In [1]:
import torch

## Indexing (Selecting data from tensor)

In [10]:
# creating tensor

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [11]:
# selecting the first index

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
x[0][1]

tensor([4, 5, 6])

In [17]:
x[0][1][1]

tensor(5)

In [21]:
# Use ':' to select all of the targeted demensions
x[:,2]

tensor([[7, 8, 9]])

In [25]:
# Get all values of 0th and 1st dimentions but only index 1 and 2nd dimentions

x[:,:,1]

tensor([[2, 5, 8]])

In [26]:
# Get all values of the 0th dimentions but only of the 1 index value of 1st and 2nd dimentions

x[:,1,1]

tensor([5])

In [33]:
# Index on x to return 9
x[0,2,2]

# Index of x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## Pytorch tensor to Numpy

In [37]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1,10)
tensor = torch.from_numpy(array)

array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [41]:
# Tensor to Numpy array
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))