In [1]:
import torch

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and
make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a
**random seed**.

Essentially what the random seed does is "flavour" the randomness.


In [3]:
# Create two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9824, 0.8728, 0.3845, 0.4893],
        [0.6273, 0.8915, 0.9406, 0.2480],
        [0.5591, 0.7635, 0.1153, 0.0011]])
tensor([[0.4123, 0.1198, 0.7216, 0.2838],
        [0.1859, 0.4230, 0.6202, 0.5445],
        [0.8995, 0.9215, 0.0131, 0.7545]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [4]:
# Set the random seed 

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
